@startuml ユースケース図
title rese ユースケース図

!theme cloudscape-design

left to right direction

skinparam actorstyle awesome

actor 利用者 #LightGreen
actor 店舗管理者 #Red

package "ユーザー入力システム" {
    usecase 会員登録
    usecase ログインとログアウト

    usecase 店舗の一覧と詳細取得
    usecase お気に入り登録と削除
    usecase 店舗の検索と予約

    usecase 利用者情報取得
    usecase 利用者お気に入り一覧取得
    usecase 利用者予約情報取得
    }
利用者 --> 店舗の一覧と詳細取得
利用者 --> ログインとログアウト
利用者 --> 会員登録
利用者 --> お気に入り登録と削除
利用者 --> 店舗の検索と予約
利用者情報取得 <-- 店舗管理者
利用者お気に入り一覧取得 <-- 店舗管理者
利用者予約情報取得 <-- 店舗管理者


package "管理システム"{
    usecase 店舗情報の作成と更新
    usecase 予約情報の確認
}
店舗管理者 --> 店舗情報の作成と更新
店舗管理者 --> 予約情報の確認
@enduml


' アクターの洗い出し
' 【利用者】
'     ・会員登録
'     ・ログイン、ログアウト

'     ・店舗の一覧と詳細取得
'     ・お気に入り登録と削除

'     ・店舗の検索（エリア、ジャンル、店名）
'     ・店舗を予約追加、削除
'     ・マイページ

' 【店舗代表者】
'     ・利用者情報取得
'     ・利用者お気に入り一覧取得
'     ・利用者予約情報取得
' 【管理者】
'     ・店舗管理者を作成


' 【エンティティ、アトリビュートの洗い出し】
'       会員（利用者情報）      [users]
'               ・名前
'               ・メールアドレス
'               ・パスワード
'       店舗                   [shops]
'               ・一覧
'               ・詳細
'               ・店舗画像
'               ・検索（エリア、ジャンル、店舗名）
'               ・お気に入り登録、解除

'       予約（予約情報）        [reservations]
'               ・名前
'               ・日時
'               ・人数
'               ・店舗情報の表示
'               ・予約情報

'       マイページ（お気に入り情報）[mypages]
'               ・名前
'               ・店舗情報
'               ・予約情報
'               ・お気に入り情報

'       管理システム            [managements]
'               ・利用者情報
'               ・利用者お気に入り一覧
'               ・利用者予約情報
